// <auto-generated />
using System;
using ASP.NetCoreWebAPI.Models.Purchase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASP.NetCoreWebAPI.Migrations
{
    [DbContext(typeof(PurchaseDb))]
    partial class PurchaseDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CH_PurchaseWpfModule.Models.BillFromPurchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompanyPurchaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PostalCharges")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyPurchaseId");

                    b.ToTable("BillFromPurchases");
                });

            modelBuilder.Entity("CH_PurchaseWpfModule.Models.CompanyPurchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaxNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PurchaseType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CompanyPurchases");
                });

            modelBuilder.Entity("CH_PurchaseWpfModule.Models.Metal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BillFromPurchaseId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MetalType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BillFromPurchaseId");

                    b.ToTable("Metals");
                });

            modelBuilder.Entity("CH_PurchaseWpfModule.Models.Plastic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BillFromPurchaseId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlaticType")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BillFromPurchaseId");

                    b.ToTable("Plastics");
                });

            modelBuilder.Entity("CH_PurchaseWpfModule.Models.BillFromPurchase", b =>
                {
                    b.HasOne("CH_PurchaseWpfModule.Models.CompanyPurchase", null)
                        .WithMany("BillFromPurchases")
                        .HasForeignKey("CompanyPurchaseId");
                });

            modelBuilder.Entity("CH_PurchaseWpfModule.Models.Metal", b =>
                {
                    b.HasOne("CH_PurchaseWpfModule.Models.BillFromPurchase", null)
                        .WithMany("Metals")
                        .HasForeignKey("BillFromPurchaseId");
                });

            modelBuilder.Entity("CH_PurchaseWpfModule.Models.Plastic", b =>
                {
                    b.HasOne("CH_PurchaseWpfModule.Models.BillFromPurchase", null)
                        .WithMany("Plastics")
                        .HasForeignKey("BillFromPurchaseId");
                });

            modelBuilder.Entity("CH_PurchaseWpfModule.Models.BillFromPurchase", b =>
                {
                    b.Navigation("Metals");

                    b.Navigation("Plastics");
                });

            modelBuilder.Entity("CH_PurchaseWpfModule.Models.CompanyPurchase", b =>
                {
                    b.Navigation("BillFromPurchases");
                });
#pragma warning restore 612, 618
        }
    }
}
